import { TIngredients } from "../../utils/types";

export const ADD_CONSTRUCTOR_INGREDIENT: "ADD_CONSTRUCTOR_INGREDIENT" =
  "ADD_CONSTRUCTOR_INGREDIENT";
export const ADD_CONSTRUCTOR_INGREDIENTS: "ADD_CONSTRUCTOR_INGREDIENTS" =
  "ADD_CONSTRUCTOR_INGREDIENTS";
export const CHANGE_CONSTRUCTOR_INGREDIENT_POSITION: "CHANGE_CONSTRUCTOR_INGREDIENT_POSITION" =
  "CHANGE_CONSTRUCTOR_INGREDIENT_POSITION";
export const REMOVE_CONSTRUCTOR_INGREDIENT: "REMOVE_CONSTRUCTOR_INGREDIENT" =
  "REMOVE_CONSTRUCTOR_INGREDIENT";

export type TConstructorIngredientsAction = {
  type: string;
  payload: TIngredients;
  index: number;
};
